name: CI Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run e2e tests
        run: npm run test:e2e:ci

      - name: Upload screenshots when specs failed
        if: ${{failure()}}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./cypress/screenshots

      - name: Upload videos when specs failed
        if: ${{failure()}}
        uses: actions/upload-artifact@v2
        with:
          name: videos
          path: ./cypress/videos
